title: Integrated Healthcare <br> Timetabling Competition <br> 2024
description: ihtc2024
theme: just-the-docs
#remote_theme: just-the-docs/just-the-docs

url: https://iihc2024.github.io
color_scheme: iihc

search_enabled: false

aux_links:
  IHTC on Github: https://github.com/iihc2024/iihc2024.github.io

markdown: kramdown

collections:
  data:
    output: false

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: 
    color: yellow
