title: International Integrated <br> Healthcare Competition <br> 2024
description: A site which hopefully will load
theme: just-the-docs

url: https://iihc2024.github.io
color_scheme: iihc

search_enabled: false

aux_links:
  IIHC on Github: https://github.com/iihc2024/iihc2024.github.io
